package com;
// Generated Mar 18, 2015 1:54:37 PM by Hibernate Tools 3.6.0


import java.sql.Blob;
import java.util.Date;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private int id;
     private String userName;
     private String fullName;
     private String password;
     private String address;
     private String phone;
     private Date birthday;
     private byte[] image;
     private Blob pic;

    public Account() {
    }

    public Account(String userName, String fullName, String password, String address, String phone, Date birthday, byte[] image, Blob pic) {
       this.userName = userName;
       this.fullName = fullName;
       this.password = password;
       this.address = address;
       this.phone = phone;
       this.birthday = birthday;
       this.image = image;
       this.pic = pic;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public Blob getPic() {
        return this.pic;
    }
    
    public void setPic(Blob pic) {
        this.pic = pic;
    }




}


