package com;
// Generated Mar 18, 2015 1:54:37 PM by Hibernate Tools 3.6.0



/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer idemployee;
     private String employeeName;
     private byte[] photo;

    public Employee() {
    }

	
    public Employee(String employeeName) {
        this.employeeName = employeeName;
    }
    public Employee(String employeeName, byte[] photo) {
       this.employeeName = employeeName;
       this.photo = photo;
    }
   
    public Integer getIdemployee() {
        return this.idemployee;
    }
    
    public void setIdemployee(Integer idemployee) {
        this.idemployee = idemployee;
    }
    public String getEmployeeName() {
        return this.employeeName;
    }
    
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }




}


